---
- name: creating mark file
  hosts: all
  become: yes

  tasks:
  - name: touching a file
    file:
      path: /root/mark_file
      owner: mark
      group: mark
      mode: '2760'
      state: touch
