---
- name: mount and format to ext4
  hosts: all
  become: yes

  tasks:
  - name: formatting to ext4
    filesystem:
      fstype: ext4
      dev: /dev/xvdf1
    when: "'prod' in group_names"

  - name: formatting to ext4
    filesystem:
      fstype: ext4
      dev: /dev/nvme1n1p1
    when: "'webservers' in group_names"
  
  - name: creating directory
    file:
      path: /mnt/partition
      state: directory
      mode: '0755'

  - name: mounting
    mount: 
      path: /mnt/partition
      src: /dev/xvdf1
      fstype: ext4
      opts: defaults
      state: mounted
    when: "'prod' in group_names"

  - name: mounting in web
    mount: 
      path: /mnt/partition
      src: /dev/nvme1n1p1
      fstype: ext4
      opts: defaults
      state: mounted
    when: "'webservers' in group_names"

