---
- name: creating the logical volume
  hosts: all
  become: yes

  tasks:
  - name: creating logical volume
    lvol:   
      vg: vgroup
      lv: vol
      size: 100%FREE
    register: vino 

  - debug:
      msg: VG does not exist in {{ inventory_hostname }}
    when: "'err' in vino"

